<?php

namespace App\Services\Iptv;

use App\Services\SyncSettings;
use Illuminate\Http\Client\Response;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;
use Throwable;

class IptvProxyPool
{
    private const CURSOR_KEY = 'pixflix:iptv-proxy-cursor';

    public function __construct(private readonly SyncSettings $settings) {}

    /**
     * @return array<int, array{id: string, name: string, base_url: string, enabled: bool, priority: int}>
     */
    public function configured(): array
    {
        $proxies = $this->settings->get('iptv.proxies', config('pixflix.iptv.proxies', []));
        if (! is_array($proxies)) {
            return [];
        }

        return collect($proxies)
            ->filter(fn (mixed $proxy): bool => is_array($proxy))
            ->map(fn (array $proxy, int $index): array => [
                'id' => trim((string) ($proxy['id'] ?? 'proxy-'.($index + 1))),
                'name' => trim((string) ($proxy['name'] ?? 'Proxy '.($index + 1))),
                'base_url' => rtrim(trim((string) ($proxy['base_url'] ?? '')), '/'),
                'enabled' => (bool) ($proxy['enabled'] ?? true),
                'priority' => (int) ($proxy['priority'] ?? ($index + 1)),
            ])
            ->filter(fn (array $proxy): bool => $proxy['base_url'] !== '' && $proxy['enabled'])
            ->sortBy('priority')
            ->values()
            ->all();
    }

    /**
     * @return array<int, array{id: string, name: string, base_url: string, enabled: bool, priority: int}>
     */
    public function configuredForAdmin(): array
    {
        $proxies = $this->settings->get('iptv.proxies', config('pixflix.iptv.proxies', []));
        if (! is_array($proxies)) {
            return [];
        }

        return collect($proxies)
            ->filter(fn (mixed $proxy): bool => is_array($proxy))
            ->map(fn (array $proxy, int $index): array => [
                'id' => trim((string) ($proxy['id'] ?? 'proxy-'.($index + 1))),
                'name' => trim((string) ($proxy['name'] ?? 'Proxy '.($index + 1))),
                'base_url' => rtrim(trim((string) ($proxy['base_url'] ?? '')), '/'),
                'enabled' => (bool) ($proxy['enabled'] ?? true),
                'priority' => (int) ($proxy['priority'] ?? ($index + 1)),
            ])
            ->filter(fn (array $proxy): bool => $proxy['base_url'] !== '')
            ->sortBy('priority')
            ->values()
            ->all();
    }

    /**
     * Tries the configured proxies in rotating order, cascading to the next
     * one whenever the previous proxy does not return a successful response.
     * With an empty pool, the stream is requested directly for compatibility.
     *
     * @param  array<string, string>  $headers
     */
    public function fetch(string $target, int $timeout, array $headers = [], bool $stream = false): ?Response
    {
        $proxies = $this->configured();
        if ($proxies === []) {
            try {
                $request = Http::timeout($timeout)
                    ->accept('*/*')
                    ->withHeaders($headers);
                if ($stream) {
                    $request = $request->withOptions(['stream' => true]);
                }
                $response = $request->get($target);
            } catch (Throwable) {
                return null;
            }

            return $response->successful() ? $response : null;
        }

        $count = count($proxies);
        $start = $this->nextStart($count);

        for ($offset = 0; $offset < $count; $offset++) {
            $proxy = $proxies[($start + $offset) % $count];

            try {
                $request = Http::timeout($timeout)
                    ->accept('*/*')
                    ->withHeaders($headers);
                if ($stream) {
                    $request = $request->withOptions(['stream' => true]);
                }
                $response = $request->get($this->proxyUrl($proxy['base_url'], $target));
            } catch (Throwable) {
                continue;
            }

            if ($response->successful()) {
                return $response;
            }
        }

        return null;
    }

    /**
     * Removes wrappers generated by a configured proxy from manifest URLs.
     * This keeps nested playlists and segments from being sent through the
     * same proxy more than once and prevents proxy credentials from reaching
     * the browser in signed stream URLs.
     */
    public function unwrap(string $target): string
    {
        $proxies = $this->configured();

        for ($depth = 0; $depth < 3; $depth++) {
            $parts = parse_url($target);
            if (! is_array($parts) || ! isset($parts['scheme'], $parts['host'])) {
                break;
            }

            $matchesProxy = collect($proxies)->contains(
                fn (array $proxy): bool => $this->sameEndpoint($parts, $proxy['base_url']),
            );
            if (! $matchesProxy) {
                break;
            }

            $query = [];
            parse_str((string) ($parts['query'] ?? ''), $query);
            $inner = $query['url'] ?? null;
            if (! is_string($inner)
                || filter_var($inner, FILTER_VALIDATE_URL) === false
                || ! in_array(parse_url($inner, PHP_URL_SCHEME), ['http', 'https'], true)) {
                break;
            }

            $target = $inner;
        }

        return $target;
    }

    private function nextStart(int $count): int
    {
        $current = (int) Cache::get(self::CURSOR_KEY, -1);
        $next = ($current + 1) % $count;
        Cache::put(self::CURSOR_KEY, $next, now()->addDay());

        return $next;
    }

    private function proxyUrl(string $baseUrl, string $target): string
    {
        $parts = parse_url($baseUrl);
        if (! is_array($parts) || ! isset($parts['scheme'], $parts['host'])) {
            return $baseUrl.'?url='.rawurlencode($target);
        }

        $query = [];
        if (isset($parts['query'])) {
            parse_str($parts['query'], $query);
        }
        $query['url'] = $target;

        $authority = $parts['scheme'].'://';
        if (isset($parts['user'])) {
            $authority .= $parts['user'];
            if (isset($parts['pass'])) {
                $authority .= ':'.$parts['pass'];
            }
            $authority .= '@';
        }
        $authority .= $parts['host'];
        if (isset($parts['port'])) {
            $authority .= ':'.$parts['port'];
        }

        return $authority.($parts['path'] ?? '/').'?'.http_build_query($query, '', '&', PHP_QUERY_RFC3986);
    }

    /** @param array<string, mixed> $targetParts */
    private function sameEndpoint(array $targetParts, string $baseUrl): bool
    {
        $baseParts = parse_url($baseUrl);
        if (! is_array($baseParts) || ! isset($baseParts['scheme'], $baseParts['host'])) {
            return false;
        }

        return strtolower((string) $targetParts['scheme']) === strtolower((string) $baseParts['scheme'])
            && strtolower((string) $targetParts['host']) === strtolower((string) $baseParts['host'])
            && (int) ($targetParts['port'] ?? 0) === (int) ($baseParts['port'] ?? 0)
            && rtrim((string) ($targetParts['path'] ?? '/'), '/') === rtrim((string) ($baseParts['path'] ?? '/'), '/');
    }
}
